# Triggers a build within the Datadog infrastructure in the ddprof-build repository
trigger_internal_build:
  rules:
    - if: $CI_PROJECT_NAME =~ /java-profiler$/
      when: never
    - if: $CI_COMMIT_BRANCH =~ /release\/.*/
      when: never
    - when: always
      allow_failure: false
  variables:
    DOWNSTREAM_BRANCH: "main"
    JPLIB_DEFAULT_BRANCH: "main"
    JPLIB_COMMIT_BRANCH: ${CI_COMMIT_BRANCH}
    JPLIB_COMMIT_SHA: ${CI_COMMIT_SHA}
    JPLIB_SHORT_COMMIT_SHA: ${CI_COMMIT_SHORT_SHA}
    JPLIB_COMMIT_TAG: ${CI_COMMIT_REF_NAME}
  trigger:
    project: DataDog/apm-reliability/async-profiler-build
    strategy: depend
    branch: $DOWNSTREAM_BRANCH