# Triggers a build within the Datadog infrastructure in the ddprof-build repository
trigger_internal_build:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /release\/.*/
      when: never
    - when: always
      allow_failure: false
  variables:
    DOWNSTREAM_BRANCH: "main"
    DDPROF_DEFAULT_BRANCH: "main"
    DDPROF_COMMIT_BRANCH: ${CI_COMMIT_BRANCH}
    DDROF_COMMIT_SHA: ${CI_COMMIT_SHA}
    DPROF_SHORT_COMMIT_SHA: ${CI_COMMIT_SHORT_SHA}
    DDPROF_COMMIT_TAG: ${CI_COMMIT_TAG}
  trigger:
    project: DataDog/apm-reliability/async-profiler-build
    strategy: depend
    branch: $DOWNSTREAM_BRANCH
    forward:
      pipeline_variables: true

# This job is used to determine is downstream pipeline has succeeded
report_failure:
  tags: ["arch:amd64"]
  when: on_failure
  needs: [trigger_internal_build]
  # allow_failure: true prevents the job from showing up in github statuses (because it's filtered by gitsync)
  allow_failure: true
  script:
    - echo "STATUS=1" >> .env
  artifacts:
    reports:
      dotenv: .env

# Final job that will show in github statuses
report_gitlab_CI_status:
  tags: ["arch:amd64"]
  when: always
  stage: .post
  script:
    - exit ${STATUS}