# Triggers a build within the Datadog infrastructure in the ddprof-build repository
trigger_internal_build:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /release\/.*/
      when: never
    - when: always
      allow_failure: false
  variables:
    DOWNSTREAM_BRANCH: "zgu/fix-benchmark"
    UPSTREAM_PROJECT: ${CI_PROJECT_PATH}
    UPSTREAM_PROJECT_NAME: ${CI_PROJECT_NAME}
    UPSTREAM_BRANCH: ${CI_COMMIT_BRANCH}
    UPSTREAM_COMMIT_SHA: ${CI_COMMIT_SHA}
    DDPROF_DEFAULT_BRANCH: "main"
    DDPROF_COMMIT_BRANCH: ${CI_COMMIT_BRANCH}
    DDROF_COMMIT_SHA: ${CI_COMMIT_SHA}
    DPROF_SHORT_COMMIT_SHA: ${CI_COMMIT_SHORT_SHA}
    DDPROF_COMMIT_TAG: ${CI_COMMIT_TAG}
  trigger:
    project: DataDog/apm-reliability/async-profiler-build
    strategy: depend
    branch: $DOWNSTREAM_BRANCH
    forward:
      pipeline_variables: true

