# Copyright 2026, Datadog, Inc.
# SPDX-License-Identifier: Apache-2.0

TARGET_DIR = ../build/test/resources/native-libs/unloadable-io-lib
all:
	gcc -fPIC -shared -o $(TARGET_DIR)/libunloadable-io.so unloadable_io.c
