#!/bin/bash
# create-image-update-pr.sh - Create GitHub PR for image updates
#
# Takes JSON output from check-image-updates.sh and creates a PR on GitHub
# with the updated image references.
#
# Usage: ./scripts/create-image-update-pr.sh [updates.json]
#        cat updates.json | ./scripts/create-image-update-pr.sh
#
# Required environment:
#   DDOCTOSTS_ID_TOKEN - GitLab OIDC token for Octo-STS (CI provides this)
#   OR
#   GITHUB_TOKEN - GitHub token with repo write access (for bootstrap)
#
# Optional environment:
#   DRY_RUN - Set to 'true' to skip PR creation

set -euo pipefail

# Configuration
GITHUB_REPO="DataDog/java-profiler"
OCTO_STS_SCOPE="DataDog/java-profiler"
OCTO_STS_POLICY="update-images"

# Colors for stderr output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $*" >&2; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*" >&2; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# Obtain GitHub token
obtain_github_token() {
    # Try Octo-STS first (preferred for CI)
    if command -v dd-octo-sts &>/dev/null && [[ -n "${DDOCTOSTS_ID_TOKEN:-}" ]]; then
        log_info "Obtaining GitHub token via Octo-STS..."
        local token
        token=$(dd-octo-sts token --scope "${OCTO_STS_SCOPE}" --policy "${OCTO_STS_POLICY}" 2>/dev/null || echo "")
        if [[ -n "$token" ]]; then
            log_info "Successfully obtained GitHub token via Octo-STS"
            echo "$token"
            return 0
        fi
        log_warn "Octo-STS token exchange failed (policy may not exist yet)"
    fi

    # Fall back to GITHUB_TOKEN environment variable
    if [[ -n "${GITHUB_TOKEN:-}" ]]; then
        log_info "Using GITHUB_TOKEN from environment"
        echo "${GITHUB_TOKEN}"
        return 0
    fi

    log_error "No GitHub authentication available"
    log_error "Either:"
    log_error "  1. Run in GitLab CI with DDOCTOSTS_ID_TOKEN configured, OR"
    log_error "  2. Set GITHUB_TOKEN environment variable (for bootstrap)"
    return 1
}

# Check if STS policy exists in the cloned repo
check_sts_policy_exists() {
    local repo_dir="$1"
    [[ -f "${repo_dir}/.github/chainguard/update-images.sts.yaml" ]]
}

# Create STS policy file content
create_sts_policy_content() {
    cat <<'EOF'
# Octo-STS Trust Policy for Image Update PRs
#
# This policy allows the GitLab CI check-image-updates job to:
# - Push branches to the repository
# - Create pull requests for image updates
#
# Trust Policy Location: .github/chainguard/update-images.sts.yaml
# Documentation: https://edu.chainguard.dev/open-source/octo-sts/

# GitLab OIDC issuer
issuer: https://gitlab.ddbuild.io

# Match GitLab CI jobs from the async-profiler-build project
# The scheduled job runs on main, but we allow any branch for manual triggers
subject_pattern: project_path:DataDog/java-profiler:ref_type:branch:ref:.*

# GitHub API permissions
permissions:
  # Required to push branches
  contents: write
  # Required to create PRs
  pull_requests: write
EOF
}

# Update a YAML file with new image reference
update_yaml_file() {
    local yaml_file="$1"
    local var_name="$2"
    local new_full_ref="$3"
    local job_url="$4"

    log_info "Updating ${var_name} in ${yaml_file}"

    # Comment format: # Generated by <job_url>
    # For .gitlab-ci.yml (GHTOOLS_IMAGE), format is just: # <job_url>
    local comment_prefix="# Generated by"
    if [[ "$yaml_file" == ".gitlab-ci.yml" ]]; then
        comment_prefix="#"
    fi

    # First, update or add the comment line before the variable
    # Look for existing comment and variable pattern
    if grep -q "^\s*${comment_prefix}.*${var_name}" "$yaml_file" 2>/dev/null || \
       grep -B1 "^\s*${var_name}:" "$yaml_file" | grep -q "^#"; then
        # Update existing comment (line before the variable)
        # Use sed with pattern matching: find the line before VAR_NAME and update it
        sed -i.bak -E "/^\s*${var_name}:/{
            x
            s|^.*$|  ${comment_prefix} ${job_url}|
            x
        }" "$yaml_file"
        rm -f "${yaml_file}.bak"
    fi

    # Update the variable value
    # Match: "  VAR_NAME: old_value" and replace with "  VAR_NAME: new_value"
    sed -i.bak -E "s|^(\s*${var_name}:).*$|\1 ${new_full_ref}|" "$yaml_file"
    rm -f "${yaml_file}.bak"
}

# More robust YAML update using line-by-line processing
update_yaml_robust() {
    local yaml_file="$1"
    local var_name="$2"
    local new_full_ref="$3"
    local job_url="$4"

    log_info "Updating ${var_name} in ${yaml_file}"

    local temp_file
    temp_file=$(mktemp)

    # Determine comment format
    local comment_line
    if [[ "$yaml_file" == ".gitlab-ci.yml" ]]; then
        comment_line="  # ${job_url}"
    else
        comment_line="  # Generated by ${job_url}"
    fi

    local prev_was_comment=false

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Check if this line is the target variable
        if [[ "$line" =~ ^[[:space:]]*${var_name}: ]]; then
            # Check if previous line was a comment we should replace
            if $prev_was_comment; then
                # Remove the last line from temp_file (the old comment)
                head -n -1 "$temp_file" > "${temp_file}.tmp"
                mv "${temp_file}.tmp" "$temp_file"
            fi
            # Write new comment and updated variable
            echo "$comment_line" >> "$temp_file"
            # Extract indentation from original line
            local indent
            indent=$(echo "$line" | sed 's/^\([[:space:]]*\).*/\1/')
            echo "${indent}${var_name}: ${new_full_ref}" >> "$temp_file"
            prev_was_comment=false
            continue
        fi

        # Track if this line is a comment (for next iteration)
        if [[ "$line" =~ ^[[:space:]]*# ]]; then
            prev_was_comment=true
        else
            prev_was_comment=false
        fi

        echo "$line" >> "$temp_file"
    done < "$yaml_file"

    mv "$temp_file" "$yaml_file"
}

# Build PR description
build_pr_description() {
    local updates_json="$1"
    local include_sts_policy="$2"

    cat <<EOF
## Summary
Updates CI image references to latest builds.

### Changes
$(echo "$updates_json" | jq -r '.[] | "- **\(.var_name)**: \(.current_tag) → \(.new_tag)"')

### Build Jobs
$(echo "$updates_json" | jq -r '.[] | select(.job_url != "") | "- [\(.var_name)](\(.job_url))"')
EOF

    if [[ "$include_sts_policy" == "true" ]]; then
        cat <<'EOFB'

### Bootstrap
This PR includes the Octo-STS policy file (`.github/chainguard/update-images.sts.yaml`)
which enables automatic authentication for future image update PRs.
EOFB
    fi

    cat <<EOF

---
*Automated by check-image-updates CI job*
EOF
}

# Check for existing open PR
check_existing_pr() {
    local gh_token="$1"

    log_info "Checking for existing open PRs..."

    local existing_pr
    existing_pr=$(GH_TOKEN="$gh_token" gh pr list \
        --repo "${GITHUB_REPO}" \
        --state open \
        --head "ci/update-images" \
        --json number,url \
        --jq '.[0].url // empty' 2>/dev/null || echo "")

    if [[ -n "$existing_pr" ]]; then
        echo "$existing_pr"
    fi
}

main() {
    local updates_file="${1:-}"

    # Read updates JSON
    local updates_json
    if [[ -n "$updates_file" ]]; then
        if [[ ! -f "$updates_file" ]]; then
            log_error "Updates file not found: $updates_file"
            exit 1
        fi
        updates_json=$(cat "$updates_file")
    else
        log_info "Reading updates from stdin..."
        updates_json=$(cat)
    fi

    # Validate JSON
    if ! echo "$updates_json" | jq empty 2>/dev/null; then
        log_error "Invalid JSON input"
        exit 1
    fi

    # Reject any entry missing a valid sha256 digest in new_full_ref
    local bad_refs
    bad_refs=$(echo "$updates_json" | jq -r '.[] | select(.new_full_ref | test("@sha256:[a-f0-9]{64}$") | not) | .var_name')
    if [[ -n "$bad_refs" ]]; then
        log_error "Refusing to create PR: the following entries have missing or invalid digest in new_full_ref:"
        echo "$bad_refs" | while read -r v; do log_error "  $v"; done
        exit 1
    fi

    # Check if there are any updates
    local update_count
    update_count=$(echo "$updates_json" | jq 'length')
    if [[ "$update_count" -eq 0 ]]; then
        log_info "No updates to apply"
        exit 0
    fi

    log_info "Processing ${update_count} image update(s)..."

    # Build PR title and description early (for dry run)
    local pr_title
    pr_title="ci: Update CI images ($(date +%Y-%m-%d))"
    local branch_name
    branch_name="ci/update-images-$(date +%Y%m%d-%H%M%S)"

    # For dry run, show what would happen without cloning
    if [[ "${DRY_RUN:-}" == "true" ]]; then
        # Assume STS policy doesn't exist for dry run display
        local include_sts_policy="true"
        local pr_body
        pr_body=$(build_pr_description "$updates_json" "$include_sts_policy")

        log_info "DRY RUN: Would create PR with:"
        log_info "  Title: ${pr_title}"
        log_info "  Branch: ${branch_name}"
        log_info "  Files that would be changed:"
        echo "$updates_json" | jq -r '.[] | "    - \(.yaml_file): \(.var_name)"'
        log_info "    - .github/chainguard/update-images.sts.yaml (bootstrap, if not exists)"
        log_info ""
        log_info "  PR Description:"
        echo "$pr_body"
        exit 0
    fi

    # Obtain GitHub token
    local gh_token
    gh_token=$(obtain_github_token) || exit 1

    # Check for existing PR
    local existing_pr
    existing_pr=$(check_existing_pr "$gh_token")
    if [[ -n "$existing_pr" ]]; then
        log_warn "An open PR already exists: ${existing_pr}"
        log_warn "Please close or merge it before creating a new one"
        exit 0
    fi

    # Create temp directory for clone
    local work_dir
    work_dir=$(mktemp -d)
    # shellcheck disable=SC2064
    trap "rm -rf '$work_dir'" EXIT

    log_info "Cloning ${GITHUB_REPO}..."
    cd "$work_dir"
    git clone --depth 1 "https://x-access-token:${gh_token}@github.com/${GITHUB_REPO}.git" repo
    cd repo

    # Check if STS policy exists
    local include_sts_policy="false"
    if ! check_sts_policy_exists "."; then
        log_info "STS policy not found, will include in PR (bootstrap)"
        include_sts_policy="true"
        mkdir -p .github/chainguard
        create_sts_policy_content > .github/chainguard/update-images.sts.yaml
    fi

    # Create branch
    log_info "Creating branch: ${branch_name}"
    git checkout -b "$branch_name"

    # Apply updates to YAML files
    echo "$updates_json" | jq -c '.[]' | while read -r update; do
        local var_name yaml_file new_full_ref job_url
        var_name=$(echo "$update" | jq -r '.var_name')
        yaml_file=$(echo "$update" | jq -r '.yaml_file')
        new_full_ref=$(echo "$update" | jq -r '.new_full_ref')
        job_url=$(echo "$update" | jq -r '.job_url // ""')

        update_yaml_robust "$yaml_file" "$var_name" "$new_full_ref" "$job_url"
    done

    # Build final PR description
    local pr_body
    pr_body=$(build_pr_description "$updates_json" "$include_sts_policy")

    # Commit changes
    git config user.email "ci@datadoghq.com"
    git config user.name "CI Bot"
    git add -A

    # Check if there are changes to commit
    if git diff --cached --quiet; then
        log_warn "No changes to commit"
        exit 0
    fi

    git commit -m "$pr_title"

    # Push branch
    log_info "Pushing branch to origin..."
    git push -u origin "$branch_name"

    # Create PR
    log_info "Creating pull request..."
    local pr_url
    pr_url=$(GH_TOKEN="$gh_token" gh pr create \
        --repo "${GITHUB_REPO}" \
        --title "$pr_title" \
        --body "$pr_body" \
        --base main \
        --head "$branch_name" \
        --draft)

    log_info "PR created: ${pr_url}"

    # Try to add label (may fail if label doesn't exist)
    GH_TOKEN="$gh_token" gh pr edit "$pr_url" --add-label "CI" 2>/dev/null || true
    GH_TOKEN="$gh_token" gh pr edit "$pr_url" --add-label "AI" 2>/dev/null || true

    echo "$pr_url"
}

main "$@"
