name: "Add or Update Comment"
description: "Adds a comment or updates it based on the given text id"

inputs:
  github-token:
    description: "Github token associated with the request"
    required: true
  commenter:
      description: "The commenter identity"
      required: true
  comment-id:
    description: "The text uniquely identifying the comment to update"
    required: true
  comment-file:
    description: "The file containing the comment in HTML format"
    required: true

runs:
  using: composite
  steps:
    - name: Add or Update GitHub comment
      uses: actions/github-script@v5
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');
          const comment_id = "${{ inputs.comment-id }}";
          const commenter = "${{ inputs.commenter }}"
          const new_comment = fs.readFileSync("${{ inputs.comment-file }}", 'utf8');
          
          // List all comments in the issue
          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });
          
          const id = `<!-- id: ${comment_id} -->`
          const content = `${id} <!-- ts: ${Date.now()} --> \n <i>&#x1F527; Report generated by ${commenter}</i>\n${new_comment}`
          // Find the comment with the search text
          const comment = comments.data.find(c => c.body.includes(id));
          
          if (comment) {
            // Update the comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: comment.id,
              body: content
            });
          } else {
            // Add a new comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: content
            });
          }