name: Extract Java and Gradle Versions
description: Versions are reported in JAVA_VERSION and GRADLE_VERSION environment variables

runs:
  using: "composite"
  steps:
    - name: Extract Versions
      id: extract_versions
      shell: bash
      run: |
        set +e

        # Extract Java version
        ${{ env.JAVA_TEST_HOME }}/bin/java -version
        JAVA_VERSION=$(${{ env.JAVA_TEST_HOME }}/bin/java -version 2>&1 | awk -F '"' '/version/ {
          split($2, v, "[._]");
          if (v[2] == "") {
            # Version is like "24": assume it is major only and add .0.0
            printf "%s.0.0\n", v[1]
          } else if (v[1] == "1") {
            # Java 8 or older: Format is "1.major.minor_update"
            printf "%s.%s.%s\n", v[2], v[3], v[4]
          } else {
            # Java 9 or newer: Format is "major.minor.patch"
            printf "%s.%s.%s\n", v[1], v[2], v[3]
          }
        }')
        echo "JAVA_VERSION=${JAVA_VERSION}"
        echo "JAVA_VERSION=${JAVA_VERSION}" >> $GITHUB_ENV

        # Extract Gradle version from gradle-wrapper.properties
        gradle_version=$(grep 'distributionUrl' gradle/wrapper/gradle-wrapper.properties | cut -d'=' -f2)
        gradle_version=${gradle_version#*gradle-}
        gradle_version=${gradle_version%-bin.zip}
        echo "GRADLE_VERSION=${gradle_version}" >> $GITHUB_ENV