# Allow async-profiler-build CI to publish to gh-pages
issuer: https://gitlab.ddbuild.io

subject_pattern: "project_path:DataDog/apm-reliability/async-profiler-build:ref_type:branch:ref:.*"

claim_pattern:
  project_path: "DataDog/apm-reliability/async-profiler-build"
  ref_type: "branch"
  ref: ".*"

permissions:
  contents: "write"
  issues: "write"
  pull_requests: "read"
