# Allow async-profiler-build CI to publish to gh-pages
issuer: https://gitlab.ddbuild.io

subject_pattern: project_path:DataDog/async-profiler-build:ref_type:branch:ref:.*
permissions:
  contents: write
  pull_requests: read