issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/java-profiler:pull_request

claim_pattern:
  event_name: pull_request_target
  ref: refs/heads/main
  ref_protected: "true"
  job_workflow_ref: DataDog/java-profiler/\.github/workflows/approve-trivial\.yml@refs/heads/main

permissions:
  contents: read
  pull_requests: write

