issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/java-profiler:ref:refs/heads/main

claim_pattern:
  event_name: (schedule|workflow_dispatch)
  ref: refs/heads/main
  job_workflow_ref: DataDog/java-profiler/\.github/workflows/upstream-tracker\.yml@refs/heads/main

permissions:
  actions: write
  contents: read
  issues: write
  metadata: read
