name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  contents: read
  issues: write
  pull-requests: read
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: aidar-freeed/ai-codereviewer@v2.7.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4o-mini"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas