name: Auto-Approve Trivial PRs

on:
  pull_request_target:
    types: [labeled]

jobs:
  auto-approve:
    if: contains(github.event.pull_request.labels.*.name, 'trivial') || contains(github.event.pull_request.labels.*.name, 'no-review')
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to federate tokens
    steps:
      - uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        id: octo-sts
        with:
          scope: DataDog/java-profiler
          policy: self.approve-trivial.approve-pr
      - name: Auto-approve PR
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # 9.0.0
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
