name: Auto-Approve Trivial PRs

on:
  pull_request_target:
    types: [labeled]

jobs:
  auto-approve:
    if: contains(github.event.pull_request.labels.*.name, 'trivial') || contains(github.event.pull_request.labels.*.name, 'no-review')
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to federate tokens
    steps:
      - uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        id: octo-sts
        with:
          scope: DataDog/java-profiler
          policy: self.approve-trivial.approve-pr
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
