name: C++ CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - run: sudo sysctl kernel.perf_event_paranoid=1
      - run: make
      - run: make test
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: hs_err_files.zip
          path: test/hs_err_*
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          path: build/
