name: Upstream
run-name: Release ${{ inputs.release_tag }} ${{ github.event.ref_name }}
on: 
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        description: "Release tag"
        required: true
  workflow_call:
    inputs:
      release_tag:
        type: string
        description: "Release tag"
        required: false
  push:
    tags:
      - v_*.*.*

jobs:
  merge-upstream:
    if: (startsWith(github.event.ref, 'refs/tags/v_') || inputs.release_tag != '') && !endsWith(github.event.ref, '-SNAPSHOT') && endsWith(github.repository, 'java-profiler-library')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_PRIVATE }}
      - name: Create Release [automatic]
        id: create_release_auto
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          generateReleaseNotes: true
          allowUpdates: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release [manual]
        id: create_release_manual
        uses: ncipollo/release-action@v1
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          generateReleaseNotes: true
          allowUpdates: true
          tag: ${{ inputs.release_tag}}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upstream release
        run: |
          if [ -z "${{ inputs.release_tag }}" ]; then
            VERSION=$(echo $GITHUB_REF_NAME | sed 's#v_##g')
          else
            VERSION=$(echo "${{ inputs.release_tag }}" | sed 's#v_##g')
          fi
          git config --global user.email "java-profiler@datadoghq.com"
          git config --global user.name "Datadog Java Profiler"
          # force checkout of the branch to merge upstream
          git checkout release/${VERSION}
          git remote add upstream git@github.com:DataDog/java-profiler.git
          git remote update
          git checkout upstream/main
          # switch to the release branch on the upstream
          git switch -c upstream/release/${VERSION}
          # and merge the downstream release branch
          git merge --allow-unrelated-histories --ff -X theirs release/${VERSION}
          # the assumption is that v_<VERSION> tag is taken from the release branch
          # push the upstream release branch to 'main' together with the tag
          git push --atomic upstream HEAD:main v_${VERSION}

  release-from-upstream:
    if: startsWith(github.event.ref, 'refs/tags/v_') && !endsWith(github.event.ref, '-SNAPSHOT') && endsWith(github.repository, 'java-profiler')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: false
          allowUpdates: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}