name: Upstream
run-name: Upstream ${{ inputs.release_branch }}
on: 
  workflow_dispatch:
    inputs:
      release_branch:
        type: string
        description: "Release branch"
        required: false
  workflow_call:
    inputs:
      release_branch:
        type: string
        description: "Release branch"
        required: false
  push:
    branches:
      - release/**
    tags:
      - v*.*.*

jobs:
  merge-upstream:
    if: (startsWith(github.event.ref, 'refs/heads/release/') || inputs.release_branch != '') && endsWith(github.repository, 'java-profiler-library')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_PRIVATE }}
      - name: Upstream release
        run: |
          if [ -z "${{ inputs.release_branch }}" ]; then
            VERSION=$(echo $GITHUB_REF_NAME | sed 's#release/##g')
          else
            VERSION=$(echo "${{ inputs.release_branch }}" | sed 's#release/##g')
          fi
          git config --global user.email "java-profiler@datadoghq.com"
          git config --global user.name "Datadog Java Profiler"
          if [ ! -z "${{ inputs.release_branch }}" ]; then
            git checkout "${{ inputs.release_branch }}"
          fi
          git remote add upstream git@github.com:DataDog/java-profiler.git
          git remote update
          git checkout upstream/main
          # switch to the release branch on the upstream
          git switch -c upstream/release/$VERSION
          # and merge the downstream release branch
          git merge --allow-unrelated-histories --ff -X theirs release/$VERSION
          # the assumption is that v<VERSION> tag is taken from the release branch
          # push the upstream relase branch to 'main' together with the tag
          git push --atomic upstream HEAD:main v${VERSION}

  release-from-upstream:
    if: startsWith(github.event.ref, 'refs/tags/v') && endsWith(github.repository, 'java-profiler')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Release
        id: create_release
        uses: nickatnight/releases-action@v3
        with:
          branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}